SKOVHUS_COLOR_BASE="%{$fg[green]%}"
SKOVHUS_COLOR_GIT="%{$fg[blue]%}"

PROMPT='$SKOVHUS_COLOR_BASE%~$SKOVHUS_COLOR_GIT$(git_prompt_info)%{$reset_color%} '

ZSH_THEME_GIT_PROMPT_PREFIX="["
ZSH_THEME_GIT_PROMPT_SUFFIX="]"
ZSH_THEME_GIT_PROMPT_DIRTY=" ✗"
ZSH_THEME_GIT_PROMPT_CLEAN=""
